"use client";

import { Poppins } from "next/font/google";
import "./globals.css";
import "animate.css";
import { Provider } from "react-redux";
import { store, persistor } from "@/store/store";
import { PersistGate } from "redux-persist/integration/react";
import { Toaster } from "@/components/ui/toaster";

const inter = Poppins({ weight: "200", subsets: ["latin"] });

const metadata: { title: string; description: string } = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <title>{metadata.title}</title>
        <body
          className={inter.className}
          style={{ backgroundColor: "#000000" }}
        >
          <PersistGate loading={null} persistor={persistor}>
            {children}
          </PersistGate>
          <Toaster />
        </body>
      </html>
    </Provider>
  );
}
