import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import "animate.css";

const inter = Manrope({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#000000" }}>
        {children}
      </body>
    </html>
  );
}
